### ISSUE TITLE
Estimation error when enabling CoinMachine extension (network does not support ENS) without whitelist

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2743]
## Steps to reproduce

1. Create new colony
2. Only install Coin Machine
3. Enable Coin Machine

## Expected behaviour

* Coin Machine can be installed without whitelist extension enabled

## Actual behaviour

![screencapture-qaxdai-colony-io-colony-colonyurl-extensions-CoinMachine-setup-2021-09-22-17_11_01 (1)](https://user-images.githubusercontent.com/89165465/134407896-82446041-422f-4728-97c2-6468dfb18cba.png)

**Comment by ArmandoGraterol** [comment]
I think you can install the coin machine extension without installing the whitelist extension, but you have to use something like `0x0000000000000000000000000000000000000000` where you input the whitelist extension address on the extension initialization params. The network error may be more related to the fact that the whitelist address param is empty

**Comment by cobordism** [comment]
![estimationerror](https://user-images.githubusercontent.com/12838530/145110589-1e2c8f67-c00d-4716-99c3-9373a2eed0fd.png)

I had the same issue via a different route. I deprecated and uninstalled a previously activated whitelist extension.

**Comment by rdig** [comment]
Why was this not closed ? As it was fixed ages ago!

@cobordism yours might be related, because if you uninstall Whitelist while coin machine is running, we set the whitelist address in the current coin machine instance to `0x0000...0000` so that might affect things.

Since this issue is assigned to you @chinins, please investigate this

**Comment by chinins** [comment]
@rdig, this should have been closed as it was indeed fixed some time ago. I will look into the latest issue as it's obviously related.

**Comment by chinins** [comment]
> ![estimationerror](https://user-images.githubusercontent.com/12838530/145110589-1e2c8f67-c00d-4716-99c3-9373a2eed0fd.png)
> 
> I have a similar issue via a different route. I deprecated and uninstalled a previously activated whitelist extension. Now I get an estimation error when attempting to buy tokens through the coin machine. Is this likely to be a related issue, or a new bug?

So can you please reinstall coin machine. It's not connected to the whitelist. It's just we had a different version deployed and had some updates since then. Please let me know if that works.

**Comment by cobordism** [comment]
I saw there was an update to coin machine available. I upgraded coin machine. 
This did not fix the problem.

I then moved to deprecate the Coin Machine extension. 
I then tried to uninstall it and I get:

```
1. Uninstall Colony Extension
Estimation error: Reverted 0x636f6c6f6e....
```

Next, I reinstalled the whitelist extension to see if that would get me unstuck. However, after installation, when I went to "enable" the whitelist, I got an estimation error again. 

I next move to deprecate the whitelist. extension. 
At this point the CoinMachine is stuck in "enabled / deprecated" status and the Whitelist is in "Disabled / deprecated".

I try to uninstall Coin Machine again I get an estimation error.
I try to uninstall the Whitelist, it works.

Coin Machine can still not be used or uninstalled.

**Comment by thycommodore** [comment]
Just wanted to add-in here, that I'm having a similar issue as @cobordism. I cannot enable Coin Machine for Roadrunner (https://qaxdai.colony.io/colony/roadrunner/extensions/CoinMachine/setup). Not currently getting an error, just go through the enable process and then it stays in a `disabled` status although the signatures were executed.

Trying to replicate on a different colony.

**Comment by rdig** [comment]
@chinins please investigate this as it keeps popping up apparently

**Comment by chinins** [comment]
> Just wanted to add-in here, that I'm having a similar issue as @cobordism. I cannot enable Coin Machine for Roadrunner (https://qaxdai.colony.io/colony/roadrunner/extensions/CoinMachine/setup). Not currently getting an error, just go through the enable process and then it stays in a `disabled` status although the signatures were executed.
> 
> Trying to replicate on a different colony.

I've just checked and it seems that it's enabled. Can you check again? Sometimes you need to refresh for the status to be updated.

**Comment by chinins** [comment]
> I saw there was an update to coin machine available. I upgraded coin machine. This did not fix the problem.
> 
> I then moved to deprecate the Coin Machine extension. I then tried to uninstall it and I get:
> 
> ```
> 1. Uninstall Colony Extension
> Estimation error: Reverted 0x636f6c6f6e....
> ```
> 
> Next, I reinstalled the whitelist extension to see if that would get me unstuck. However, after installation, when I went to "enable" the whitelist, I got an estimation error again.
> 
> I next move to deprecate the whitelist. extension. At this point the CoinMachine is stuck in "enabled / deprecated" status and the Whitelist is in "Disabled / deprecated".
> 
> I try to uninstall Coin Machine again I get an estimation error. I try to uninstall the Whitelist, it works.
> 
> Coin Machine can still not be used or uninstalled.

Aron, I've joined your colony. Can you please give me the permissions so I can play around the extensions if necessary?
My username is feola.

**Comment by cobordism** [comment]
https://qaxdai.colony.io/colony/topologic/tx/0xdce06099a9d6e539d130006ad02322fab79698b24ba4a0814d346dcf614ae59c
